name: Compile FEXCore Armv9-a / cortex-x2 (exynos2200)

on:
  workflow_dispatch:

jobs:
  compile-fexcore:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
         
      - name: Install Nix Package Manager
        uses: cachix/install-nix-action@v31
        with:
         nix_path: nixpkgs=channel:nixos-unstable
        
      - name: Compile FEXCore
        run: |
          mkdir -p build/arm64ec && cd build/arm64ec
          ../../Data/nix/cmake_configure_woa64.sh ../../ -G Ninja \
            -DTUNE_ARCH="armv9-a" \
            -DTUNE_CPU="cortex-x2"
          ninja
          mkdir ../wow64 && cd ../wow64
          ../../Data/nix/cmake_configure_woa32.sh ../../ -G Ninja \
            -DTUNE_ARCH="armv9-a" \
            -DTUNE_CPU="cortex-x2"
          ninja

      - name: Package FEXCore DLLs and WCP
        run: |
          mkdir FEXCore_DLLs
          cp -r ./build/arm64ec/Bin/libarm64ecfex.dll ./FEXCore_DLLs
          cp -r ./build/wow64/Bin/libwow64fex.dll ./FEXCore_DLLs

          mkdir -p FEXCore_WCP/system32
          cp -r ./build/arm64ec/Bin/libarm64ecfex.dll ./FEXCore_WCP/system32
          cp -r ./build/wow64/Bin/libwow64fex.dll ./FEXCore_WCP/system32
          wget https://github.com/TGP-17/wcp-template/raw/refs/heads/main/FEXCore/profile.json
          mv profile.json ./FEXCore_WCP
          cd FEXCore_WCP
          TODAY=$(date +'%y%m%d')
          jq ".versionCode = $TODAY" profile.json > temp.json && mv temp.json profile.json
          tar --zstd -cf FEXCore-Nightly-$TODAY.wcp profile.json system32
          mv FEXCore-Nightly-$TODAY.wcp ../FEXCore_DLLs

      - name: Upload FEXCore_DLLs
        uses: actions/upload-artifact@v4
        with:
         name: FEXCore DLLs
         path: ./FEXCore_DLLs

      - name: "Set Date Variable"
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_ENV

      - name: "Create Release"
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
         name: "FEXCore-Nightly-${{ env.date }}"
         tag_name: "${{ env.date }}"
         prerelease: false
         files: |
          ./FEXCore_DLLs/FEXCore-Nightly*.wcp
          ./FEXCore_DLLs/libarm64ecfex.dll
          ./FEXCore_DLLs/libwow64fex.dll
